export const GET_FINES_STARTED = 'GET_FINES_STARTED'
export const GET_FINES_COMPLETED = 'GET_FINES_COMPLETED'
export const GET_FINES_FAILED = 'GET_FINES_FAILED'

export const GET_VEHICLES_STARTED = 'GET_VEHICLES_STARTED'
export const GET_VEHICLES_COMPLETED = 'GET_VEHICLES_COMPLETED'
export const GET_VEHICLES_FAILED = 'GET_VEHICLES_FAILED'
